<?php

use App\Http\Controllers\KeywordHubController;
use App\Http\Controllers\LearnPageController;
use App\Http\Controllers\PricePageController;
use App\Http\Controllers\SitemapController;
use Illuminate\Support\Facades\Route;

Route::get('/sitemap.xml', SitemapController::class);
Route::get('/blog/feed.xml', [LearnPageController::class, 'feed']);
Route::get('/blog', [LearnPageController::class, 'index'])->middleware('throttle:blog');
Route::get('/blog/search-index.json', [LearnPageController::class, 'searchIndexJson'])->middleware('throttle:blog-search-index');
Route::redirect('/blog/18k-gold', '/blog/guide-gold-karat-purity-18k-vs-24k', 301);
Route::redirect('/blog/24k-gold', '/blog/guide-gold-karat-purity-18k-vs-24k', 301);
Route::redirect('/blog/gold-karat-difference', '/blog/guide-gold-karat-purity-18k-vs-24k', 301);
Route::redirect('/blog/24k-vs-18k-gold-investment', '/blog/guide-gold-karat-purity-18k-vs-24k', 301);
Route::redirect('/blog/gold-coin-vacuum-package', '/blog/gold-coin-guide', 301);
Route::redirect('/blog/how-gold-price-is-set', '/blog/guide-gold-pricing-iran-market', 301);
Route::redirect('/blog/gold-price-factors', '/blog/guide-gold-pricing-iran-market', 301);
Route::redirect('/blog/gold-price-guide', '/blog/guide-gold-pricing-iran-market', 301);
Route::redirect('/blog/gold-mozaneh', '/blog/guide-gold-pricing-iran-market', 301);
Route::redirect('/blog/gold-price-calculation', '/blog/guide-gold-price-formulas', 301);
Route::redirect('/blog/melted-gold-price-calculation', '/blog/guide-gold-price-formulas', 301);
Route::redirect('/blog/gold-ounce-mesghal', '/blog/guide-gold-price-formulas', 301);
Route::redirect('/blog/gold-difference-buy-sell', '/blog/guide-gold-price-formulas', 301);
Route::redirect('/blog/buy-sell-gold-price-spread', '/blog/guide-gold-price-formulas', 301);
Route::redirect('/blog/melted-guide-gold-price-formulas', '/blog/guide-gold-price-formulas', 301);
Route::redirect('/blog/gold-vat', '/blog/guide-gold-invoice-tax-1405', 301);
Route::redirect('/blog/gold-tax-invoice-1405-guide', '/blog/guide-gold-invoice-tax-1405', 301);
Route::redirect('/blog/seller-profit-in-gold-invoice', '/blog/guide-gold-invoice-tax-1405', 301);
Route::redirect('/blog/used-vs-new-gold', '/blog/guide-second-hand-gold', 301);
Route::redirect('/blog/second-hand-gold-buying-checklist', '/blog/guide-second-hand-gold', 301);
Route::redirect('/blog/second-hand-gold-without-invoice', '/blog/guide-second-hand-gold', 301);
Route::redirect('/blog/is-no-wage-gold-always-better', '/blog/guide-second-hand-gold', 301);
Route::redirect('/blog/why-some-gold-loses-more-on-resale', '/blog/guide-second-hand-gold', 301);
Route::redirect('/blog/melted-gold-or-used-gold-investment', '/blog/guide-second-hand-gold', 301);
Route::redirect('/blog/digital-gold-platform-guide', '/blog/guide-digital-gold-iran', 301);
Route::redirect('/blog/digital-gold-license-checklist', '/blog/guide-digital-gold-iran', 301);
Route::redirect('/blog/digital-gold-physical-delivery-guide', '/blog/guide-digital-gold-iran', 301);
Route::redirect('/blog/digital-gold-fees-spread-guide', '/blog/guide-digital-gold-iran', 301);
Route::redirect('/blog/digital-gold-custody-risk-guide', '/blog/guide-digital-gold-iran', 301);
Route::redirect('/blog/digital-gold-empty-selling-risk', '/blog/guide-digital-gold-iran', 301);
Route::redirect('/blog/digital-gold-vs-etf-vs-physical', '/blog/guide-digital-gold-iran', 301);
Route::redirect('/blog/digital-gold-tax-invoice-records', '/blog/guide-digital-gold-iran', 301);
Route::redirect('/blog/digital-gold-small-saving-plan', '/blog/guide-digital-gold-iran', 301);
Route::redirect('/blog/digital-gold-app-trust-checklist', '/blog/guide-digital-gold-iran', 301);
Route::redirect('/blog/gold-investment-short-term-guide', '/blog/guide-gold-investment-strategies', 301);
Route::redirect('/blog/gold-investment-long-term-guide', '/blog/guide-gold-investment-strategies', 301);
Route::redirect('/blog/gold-investment-portfolio-allocation', '/blog/guide-gold-investment-strategies', 301);
Route::redirect('/blog/coin-vs-gold-short-term', '/blog/guide-gold-investment-strategies', 301);
Route::redirect('/blog/gold-dca-investment-strategy', '/blog/guide-gold-investment-strategies', 301);
Route::redirect('/blog/gold-investment-risk-management', '/blog/guide-gold-investment-strategies', 301);
Route::redirect('/blog/gold-investment-exit-strategy', '/blog/guide-gold-investment-strategies', 301);
Route::redirect('/blog/gold-vs-dollar-investment-iran', '/blog/guide-gold-investment-strategies', 301);
Route::redirect('/blog/gold-etf-short-term-trading-risks', '/blog/guide-gold-investment-strategies', 301);
Route::redirect('/blog/gold-investment-mistakes-beginners', '/blog/guide-gold-investment-strategies', 301);
Route::get('/blog/{slug}', [LearnPageController::class, 'show'])->where('slug', '[a-z0-9-]+');
Route::get('/', PricePageController::class);
Route::get('/price/mozaneh', fn() => app(KeywordHubController::class)('mozaneh'));
Route::get('/price/coin-bubble', fn() => app(KeywordHubController::class)('coin-bubble'));
Route::get('/price/ounce', fn() => app(KeywordHubController::class)('ounce'));
Route::get('/price/', PricePageController::class);
Route::get('/price/trends/{range}', PricePageController::class)->where('range', '[0-9]+[hd]?');
